### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by GTREDITION** [ray-1337/youtube-discord-embed#4]
Hello
at day 17 of september of 2024 the embled isn't working anymore
i tried to use a link like this https://yt.cdn.13373333.one/watch?v=CQzYhMDNLPA and it goes to your main profile instead this repository
please when you can, fix it otherwise if you are not going to continue the project, let me know it
thanks for your work

have a good day

**Comment by ray-1337** [comment]
Hello, the embed should be working now.
