### ISSUE TITLE
Not working as of yesterday

### ISSUE THREAD

**Issue by SpoogLord** [ray-1337/youtube-discord-embed#5]
I use [Social Media Link Converter](https://github.com/RoyRiv3r/SocialMediaLinkConverter.plugin.js), which seems to use this(?) repo in some way? In any case as of about yesterday converted youtube links started to redirect to your github profile page, which is why i believe this is somehow an issue with something in this repo rather than the previously mentioned plugin. (could be wrong tho, i didnt look at any code.)

as an example of one of the links
generated link: [https://yt.cdn.13373333.one/watch?v=d_UNYSV8O7Q&dearrow?si=v89J9M0OGRCjHsuq](https://yt.cdn.13373333.one/watch?v=d_UNYSV8O7Q&dearrow?si=v89J9M0OGRCjHsuq)
original link: [https://youtu.be/d_UNYSV8O7Q?si=tNue5AcFq9F8A3uD](https://youtu.be/d_UNYSV8O7Q?si=tNue5AcFq9F8A3uD)

if by some chance you believe this isnt an issue with your code and is rather an issue with the plugin, let me know and ill take my issue there

**Comment by ray-1337** [comment]
hello.

yeah, i believe it's not an issue from this repo, but rather from [@distube/ytdl-core](https://github.com/distubejs/ytdl-core/issues/110) itself, but don't worry, i've temporarily fixed it, so the URL should be working again now.

**Comment by SpoogLord** [comment]
I once again am being redirected to your github. 
Looking at the repo you linked before i wanna say it has something to do with their update earlier today?

**Comment by ray-1337** [comment]
yeah, YouTube changed something again recently, the issue should be fixed again for now

**Comment by QuentinMcCarthy** [comment]
I'm having the same issue, even the links on the README are redirecting to your GitHub.

**Comment by QuentinMcCarthy** [comment]
Why close this? It's not fixed.

**Comment by SpoogLord** [comment]
this issue was opened for the same issue currently happening _as it happened previously_. 
i made this issue thread in early October, the issue was fixed, the same problem happened again in late October, i commented here, the issue was fixed again, the issue is happening a third time now (at least), someone else made an issue, i didn't see a reason to comment in my own issue as it had already been reported, i closed this issue as the problem was long since fixed for the case this thread was made for. 

the issue thread for the current instance of this problem is #6 

edit: i guess more like mid october rather than early.

**Comment by ray-1337** [comment]
there are lots of changes on YouTube platform lately, and i cannot figure it out why. i'll reopen this issue for now.

**Comment by ray-1337** [comment]
and now, it's Discord issue. (edited)

![image](https://github.com/user-attachments/assets/d99c5f88-f002-4775-ac10-7c932b17f890)
